# Generated by Django 3.1.5 on 2021-01-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_auto_20210114_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
