# Generated by Django 3.1.5 on 2021-01-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='post_ingredients',
            field=models.ManyToManyField(to='theblog.Ingredient'),
        ),
    ]
