# Generated by Django 3.1.5 on 2021-01-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_auto_20210118_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_ingredients',
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.ManyToManyField(related_name='blog_post', to='theblog.Ingredient'),
        ),
    ]
